### ISSUE TITLE
Change the name/description of NetBeans plugin

### ISSUE THREAD

**Issue by arun-gupta** [arun-gupta/couchbase-netbeans-plugin#18]
NetBeans Plugins dialog shows the name of the plugin as "NetBeansCouchbase". It should be a more meaningful name as "Couchbase NoSQL Document database plugin".

Also need to add a description.

**Comment by GeertjanWielenga** [comment]
Added this to POM:
    <name>Couchbase NoSQL Document Database</name>
    <description>Provides support in NetBeans IDE for usage of the Couchbase NoSQL Document Database.</description>
